export { default as SelectedPersonal } from "./components/SelectedPersonal/SelectedPersonal"
export { default as SelectedTable } from "./components/SelectedTable/SelectedTable"
export { default as useInitialGetData } from "./hooks/useInitialGetData"
export { default as Orders } from "./Orders"
export { default as getAllOrders } from "./services/getAllOrders"
